import notionLogo from "./appLogos/Notion.webp";
import LinearLogo from "./appLogos/Linear.webp";
import CursorLogo from "./appLogos/Cursor.webp";
import PostgresdotnewLogo from "./appLogos/Postgresdotnew.webp";
import V0Logo from "./appLogos/V0.webp";
import ChatGPTLogo from "./appLogos/ChatGPT.webp";
import ClaudeLogo from "./appLogos/Claude.webp";
import FigmaLogo from "./appLogos/Figma.webp";
import HalideLogo from "./appLogos/Halide.webp";
import PhotoshopLogo from "./appLogos/Photoshop.webp";
import CloudflareLogo from "./appLogos/Cloudflare.webp";

export const appsData = [
  {
    id: "raycast",
    name: "Raycast",
    category: "Productivity",
    icon: notionLogo,
    link: "https://www.raycast.com/",
    price: "Free",
    useCase: "Quick access to system functions, apps, and custom scripts",
    description: "A productivity tool that replaces your macOS Spotlight",
    whyLike: "Faster than Spotlight with extensive customization options",
  },
  {
    id: "flightly",
    name: "Flightly",
    category: "Other",
    icon: notionLogo,
    link: "https://flightly.com/",
    price: "Free",
    useCase: "Tracking and managing flight information",
    description: "A flight tracking and management app",
    whyLike: "Simplifies travel planning and provides real-time flight updates",
  },
  {
    id: "dime",
    name: "Dime",
    category: "Other",
    icon: notionLogo,
    link: "https://apps.apple.com/sg/app/dime-budget-expense-tracker/id1635280255?ign-itscg=30200&ign-itsct=apps_box_promote_link",
    price: "Free",
    useCase: "Personal finance management and expense tracking",
    description: "A budget and expense tracking app",
    whyLike: "User-friendly interface and comprehensive financial insights",
  },

  {
    id: "notion",
    name: "Notion",
    category: "Productivity",
    icon: notionLogo,
    link: "https://www.notion.so/",
    price: "Free",
    useCase: "Note-taking, project management, and knowledge base",
    description:
      "A versatile tool for note-taking, project management, and knowledge base",
    whyLike: "Flexible and customizable, with a wide range of integrations",
  },
  {
    id: "notion-calendar",
    name: "Notion Calendar",
    category: "Productivity",
    icon: notionLogo,
    link: "https://www.notion.so/product/calendar",
    price: "Free",
    useCase: "Integrated calendar and scheduling within Notion",
    description:
      "A calendar feature for Notion, enabling seamless scheduling and event management",
    whyLike:
      "Efficiently manage your schedule and tasks within the Notion platform",
  },
  {
    id: "passwords",
    name: "Passwords",
    category: "Productivity",
    icon: notionLogo,
    link: "https://apps.apple.com/us/app/passwords/id6473799789",
    price: "Free",
    useCase: "Securely store and manage passwords",
    description: "A password manager app for iOS",
    whyLike:
      "Provides strong security features and seamless integration with other apps",
  },
  {
    id: "photoshop",
    name: "Photoshop",
    category: "Creativity",
    icon: PhotoshopLogo,
    link: "https://www.adobe.com/products/photoshop.html",
    price: "Free",
    useCase: "Professional image editing and design",
    description: "A powerful digital art and design tool",
    whyLike: "Wide range of features for advanced image editing and design",
  },
  {
    id: "iCloud",
    name: "iCloud",
    category: "Productivity",
    icon: notionLogo,
    link: "https://www.icloud.com/",
    price: "Free",
    useCase: "Cloud storage and backup for Apple devices",
    description: "Apple's cloud storage and backup service",
    whyLike:
      "Seamless integration with Apple devices and easy access to your data",
  },
  {
    id: "figma",
    name: "Figma",
    category: "Creativity",
    icon: FigmaLogo,
    link: "https://www.figma.com/",
    price: "Free",
    useCase: "Collaborative design and prototyping",
    description:
      "A collaborative design tool for creating user interfaces and prototypes",
    whyLike: "Real-time collaboration and a wide range of design tools",
  },
  {
    id: "arc",
    name: "Arc",
    category: "Productivity",
    icon: notionLogo,
    link: "https://arc.net/",
    price: "Free",
    useCase: "Browser for macOS with a focus on privacy and speed",
    description: "A privacy-focused and fast web browser for macOS",
    whyLike:
      "Prioritizes privacy and offers a clean and fast browsing experience",
  },
  {
    id: "tana",
    name: "Tana",
    category: "Productivity",
    icon: notionLogo,
    link: "https://tana.inc/",
    price: "Free",
    useCase: "Note-taking and knowledge management",
    description: "A note-taking and knowledge management app",
    whyLike:
      "Offers a unique and flexible approach to note-taking and organization",
  },
  {
    id: "reader",
    name: "Reader",
    category: "Information and Research",
    icon: notionLogo,
    link: "https://readwise.io/read",
    price: "Free",
    useCase: "Highlighting and summarizing articles for efficient reading",
    description: "A tool for highlighting and summarizing articles",
    whyLike: "Helps users extract key insights from articles and save time",
  },
  {
    id: "readwise",
    name: "Readwise",
    category: "Information and Research",
    icon: notionLogo,
    link: "https://readwise.io/",
    price: "Free",
    useCase: "Summarizing and organizing articles for efficient reading",
    description: "A tool for summarizing and organizing articles",
    whyLike:
      "Provides users with a curated collection of article summaries for easy reference",
  },
  {
    id: "youtube",
    name: "YouTube",
    category: "Entertainment",
    icon: notionLogo,
    link: "https://www.youtube.com/",
    price: "Free",
    useCase: "Watching videos and streaming content",
    description: "A popular video-sharing platform",
    whyLike: "Wide range of content and easy access to videos",
  },
  {
    id: "nebula",
    name: "Nebula",
    category: "Entertainment",
    icon: notionLogo,
    link: "https://nebula.tv/",
    price: "Free",
    useCase: "Streaming movies and TV shows",
    description: "A streaming service for movies and TV shows",
    whyLike: "Offers a wide range of content and a user-friendly interface",
  },
  {
    id: "kindle",
    name: "Kindle",
    category: "Information and Research",
    icon: notionLogo,
    link: "https://www.amazon.com/b?ie=UTF8&node=16571048011",
    price: "Free",
    useCase: "Reading e-books and digital books",
    description: "A platform for reading e-books and digital books",
    whyLike: "Wide range of books and a user-friendly reading experience",
  },
  {
    id: "refind",
    name: "Refind",
    category: "Information and Research",
    icon: notionLogo,
    link: "https://refind.com/",
    price: "Free",
    useCase: "Discovering and searching for articles and news",
    description:
      "A search engine for discovering and searching for articles and news",
    whyLike: "Provides a curated selection of articles and news sources",
  },
  {
    id: "cursor",
    name: "Cursor",
    category: "Development",
    icon: CursorLogo,
    link: "https://cursor.com/",
    price: "Free",
    useCase: "Developing and managing code",
    description: "A code editor with AI-powered features",
    whyLike:
      "Offers AI-powered code completion and intelligent code suggestions",
  },
  {
    id: "postman",
    name: "Postman",
    category: "Development",
    icon: CursorLogo,
    link: "https://www.postman.com/",
    price: "Free",
    useCase: "Testing and documenting APIs",
    description: "A tool for testing and documenting APIs",
    whyLike:
      "Provides a user-friendly interface for testing and documenting APIs",
  },
  {
    id: "warp",
    name: "Warp",
    category: "Development",
    icon: CursorLogo,
    link: "https://www.warp.dev/",
    price: "Free",
    useCase: "Developing and managing code in the terminal",
    description: "A terminal emulator with advanced features",
    whyLike:
      "Offers a modern and feature-rich terminal emulator for developers",
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "Development",
    icon: CursorLogo,
    link: "https://vercel.com/",
    price: "Free",
    useCase: "Deploying and hosting web applications",
    description: "A platform for deploying and hosting web applications",
    whyLike: "Offers easy deployment and hosting for web applications",
  },
  {
    id: "nextjs",
    name: "Next.js",
    category: "Development",
    icon: CursorLogo,
    link: "https://nextjs.org/",
    price: "Free",
    useCase: "Building server-side rendered React applications",
    description:
      "A framework for building server-side rendered React applications",
    whyLike:
      "Provides a simple and efficient way to build server-side rendered React applications",
  },
  {
    id: "expo",
    name: "Expo",
    category: "Development",
    icon: CursorLogo,
    link: "https://expo.dev/",
    price: "Free",
    useCase: "Building and deploying React Native applications",
    description:
      "A framework for building and deploying React Native applications",
    whyLike:
      "Offers a simple and efficient way to build and deploy React Native applications",
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "Development",
    icon: CursorLogo,
    link: "https://stripe.com/",
    price: "Free",
    useCase: "Integrating payment processing into web applications",
    description: "A payment processing platform",
    whyLike:
      "Provides a simple and secure way to integrate payment processing into web applications",
  },
  {
    id: "github",
    name: "GitHub",
    category: "Development",
    icon: CursorLogo,
    link: "https://github.com/",
    price: "Free",
    useCase: "Hosting and managing Git repositories",
    description: "A platform for hosting and managing Git repositories",
    whyLike:
      "Provides a wide range of features for hosting and managing Git repositories",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "Development",
    icon: CloudflareLogo,
    link: "https://www.cloudflare.com/",
    price: "Free",
    useCase: "Improving website performance and security",
    description: "A platform for improving website performance and security",
    whyLike:
      "Offers features such as caching, DDoS protection, and CDN services",
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "Development",
    icon: CursorLogo,
    link: "https://supabase.com/",
    price: "Free",
    useCase: "Building and managing databases for web applications",
    description:
      "A platform for building and managing databases for web applications",
    whyLike:
      "Provides a simple and efficient way to build and manage databases for web applications",
  },
  {
    id: "linear",
    name: "Linear",
    category: "Productivity",
    icon: LinearLogo,
    link: "https://linear.app/",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
    useCase: "Managing and organizing projects and tasks",
    whyLike:
      "Offers a simple and intuitive interface for managing and organizing projects and tasks",
  },
  {
    id: "v0",
    name: "V0",
    category: "AI",
    icon: V0Logo,
    link: "https://v0.dev/",
    price: "Free",
    description: "V0 is an AI-powered design tool.",
    useCase: "Designing user interfaces and prototypes using AI",
    whyLike:
      "Offers AI-powered features for designing user interfaces and prototypes",
  },
  {
    id: "chatgpt",
    name: "Chat GPT",
    category: "AI",
    icon: ChatGPTLogo,
    link: "https://chat.openai.com/",
    price: "Free",
    description: "ChatGPT is an AI-powered chatbot.",
    useCase: "Interacting with an AI-powered chatbot for various tasks",
    whyLike:
      "Provides a convenient and efficient way to interact with an AI-powered chatbot",
  },
  {
    id: "postgresnew",
    name: "postgres.new",
    category: "AI",
    icon: PostgresdotnewLogo,
    link: "https://postgres.new/",
    price: "Free",
    useCase: "Creating and managing PostgreSQL databases",
    description: "A platform for creating and managing PostgreSQL databases",
    whyLike:
      "Offers a simple and efficient way to create and manage PostgreSQL databases",
  },
  {
    id: "claude",
    name: "Claude",
    category: "AI",
    icon: ClaudeLogo,
    link: "https://www.anthropic.com/claude",
    price: "Free",
    description: "Claude is an AI assistant created by Anthropic.",
    useCase: "Interacting with an AI assistant for various tasks",
    whyLike:
      "Provides a convenient and efficient way to interact with an AI assistant",
  },
  {
    id: "tailwind",
    name: "Tailwind",
    category: "Development",
    icon: LinearLogo,
    link: "https://tailwindcss.com/",
    price: "Free",
    description: "Tailwind is a utility-first CSS framework.",
    useCase: "Styling web applications using a utility-first CSS framework",
    whyLike:
      "Offers a simple and efficient way to style web applications using a utility-first CSS framework",
  },
  {
    id: "x",
    name: "X",
    category: "Social Media",
    icon: LinearLogo,
    link: "https://twitter.com/",
    price: "Free",
    description: "X (formerly Twitter) is a social media platform.",
    useCase: "Sharing updates, news, and content on a social media platform",
    whyLike:
      "Provides a convenient and efficient way to share updates, news, and content on a social media platform",
  },
  {
    id: "goodreads",
    name: "Goodreads",
    category: "Social Media",
    icon: LinearLogo,
    link: "https://www.goodreads.com/user/show/92633673-thomas-harmond/",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
    useCase: "Discovering, tracking, and reviewing books",
    whyLike:
      "Provides a convenient and efficient way to discover, track, and review books",
  },
  {
    id: "reddit",
    name: "Reddit",
    category: "Social Media",
    icon: LinearLogo,
    link: "https://www.reddit.com/",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
    useCase: "Sharing and discussing content on a social media platform",
    whyLike:
      "Provides a convenient and efficient way to share and discuss content on a social media platform",
  },
  {
    id: "instagram",
    name: "Instagram",
    category: "Social Media",
    icon: LinearLogo,
    link: "https://www.instagram.com/thomas.harmond/",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
    useCase: "Sharing photos and videos on a social media platform",
    whyLike:
      "Provides a convenient and efficient way to share photos and videos on a social media platform",
  },
  {
    id: "dribbble",
    name: "Dribbble",
    category: "Social Media",
    icon: LinearLogo,
    link: "https://dribbble.com/",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
    useCase: "Discovering, sharing, and collaborating on design work",
    whyLike:
      "Provides a convenient and efficient way to discover, share, and collaborate on design work",
  },
  {
    id: "arc-search",
    name: "Arc Search",
    category: "Productivity",
    icon: LinearLogo,
    link: "https://arc.net/search",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
    useCase: "Searching the web using a privacy-focused browser",
    whyLike:
      "Provides a convenient and efficient way to search the web using a privacy-focused browser",
  },
  {
    id: "mail",
    name: "Mail",
    category: "Productivity",
    icon: LinearLogo,
    link: "https://www.icloud.com/mail",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
    useCase: "Managing and organizing emails",
    whyLike:
      "Provides a simple and efficient way to manage and organize emails",
  },
  {
    id: "notes",
    name: "Notes",
    category: "Productivity",
    icon: LinearLogo,
    link: "https://www.icloud.com/notes/",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
    useCase: "Taking and organizing notes",
    whyLike: "Provides a simple and efficient way to take and organize notes",
  },
  {
    id: "reminders",
    name: "Reminders",
    category: "Productivity",
    icon: LinearLogo,
    link: "https://www.icloud.com/reminders/",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
    useCase: "Setting and managing reminders",
    whyLike: "Provides a simple and efficient way to set and manage reminders",
  },
  {
    id: "halide",
    name: "Halide",
    category: "Creativity",
    icon: HalideLogo,
    link: "https://halide.cam/",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
    useCase: "Capturing and editing photos",
    whyLike: "Provides a simple and efficient way to capture and edit photos",
  },
  {
    id: "spotify",
    name: "Spotify",
    category: "Entertainment",
    icon: LinearLogo,
    link: "https://www.spotify.com/",
    price: "Free",
    description: "Spotify is a music streaming service.",
    useCase: "Listening to music and podcasts",
    whyLike: "Provides a wide range of music and podcasts for streaming",
  },
  {
    id: "logos",
    name: "Logos",
    category: "Information and Research",
    icon: LinearLogo,
    link: "https://logos.com/",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
    useCase: "Searching for and downloading logos",
    whyLike:
      "Provides a convenient and efficient way to search for and download logos",
  },
  {
    id: "elicit",
    name: "Elicit",
    category: "Information and Research",
    icon: LinearLogo,
    link: "https://elicit.com/",
    price: "Free",
    description: "Helps you find research papers.",
    useCase: "Discovering and searching for research papers",
    whyLike:
      "Provides a convenient and efficient way to discover and search for research papers",
  },
  {
    id: "zotero",
    name: "Zotero",
    category: "Information and Research",
    icon: LinearLogo,
    link: "https://www.zotero.org/",
    price: "Free",
    description: "Helps you manage your research papers.",
    useCase: "Managing and organizing research papers",
    whyLike:
      "Provides a simple and efficient way to manage and organize research papers",
  },
  {
    id: "anki",
    name: "Anki",
    category: "Information and Research",
    icon: LinearLogo,
    link: "https://apps.ankiweb.net/",
    price: "Free",
    description: "Helps you memorise things.",
    useCase: "Creating and studying flashcards for efficient learning",
    whyLike:
      "Provides a simple and efficient way to create and study flashcards for efficient learning",
  },
  {
    id: "connected-papers",
    name: "Connected Papers",
    category: "Information and Research",
    icon: LinearLogo,
    link: "https://www.connectedpapers.com/",
    price: "Free",
    description: "Helps you find research papers.",
    useCase: "Discovering and searching for research papers",
    whyLike:
      "Provides a convenient and efficient way to discover and search for research papers",
  },
  {
    id: "libby",
    name: "Libby",
    category: "Information and Research",
    icon: LinearLogo,
    link: "https://libbyapp.com/",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
    useCase: "Borrowing e-books from libraries",
    whyLike:
      "Provides a convenient and efficient way to borrow e-books from libraries",
  },
  {
    id: "sequel",
    name: "Sequel",
    category: "Entertainment",
    icon: LinearLogo,
    link: "https://www.getsequel.app/",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
    useCase: "Discovering and watching movies and TV shows",
    whyLike:
      "Provides a convenient and efficient way to discover and watch movies and TV shows",
  },
  {
    id: "shortcuts",
    name: "Shortcuts",
    category: "Productivity",
    icon: LinearLogo,
    link: "https://apps.apple.com/us/app/shortcuts/id915249334",
    price: "Free",
    description: "Apple's built-in automation app for iOS",
    useCase: "Automating repetitive tasks on iOS devices",
    whyLike:
      "Provides a simple and efficient way to automate repetitive tasks on iOS devices",
  },
];
