import notionLogo from "./appLogos/Notion.webp";
import LinearLogo from "./appLogos/Linear.webp";
import CursorLogo from "./appLogos/Cursor.webp";

export const appsData = [
  {
    id: "raycast",
    name: "Raycast",
    category: "Productivity",
    icon: notionLogo,
    href: "/apps/raycast",
    price: "Free",
  },
  {
    id: "notion",
    name: "Notion",
    category: "Productivity",
    icon: notionLogo,
    href: "/apps/notion",
    price: "Free",
  },
  {
    id: "notion-calendar",
    name: "Notion Calendar",
    category: "Productivity",
    icon: notionLogo,
    href: "/apps/notion-calendar",
    price: "Free",
  },
  {
    id: "passwords",
    name: "Passwords",
    category: "Productivity",
    icon: notionLogo,
    href: "/apps/passwords",
    price: "Free",
  },
  {
    id: "photoshop",
    name: "Photoshop",
    category: "Creativity",
    icon: notionLogo,
    href: "/apps/photoshop",
    price: "Free",
  },
  {
    id: "iCloud",
    name: "iCloud",
    category: "Productivity",
    icon: notionLogo,
    href: "/apps/iCloud",
    price: "Free",
  },
  {
    id: "figma",
    name: "Figma",
    category: "Creativity",
    icon: notionLogo,
    href: "/apps/figma",
    price: "Free",
  },
  {
    id: "arc",
    name: "Arc",
    category: "Productivity",
    icon: notionLogo,
    href: "/apps/arc",
    price: "Free",
  },
  {
    id: "tana",
    name: "Tana",
    category: "Productivity",
    icon: notionLogo,
    href: "/apps/tana",
    price: "Free",
  },
  {
    id: "reader",
    name: "Reader",
    category: "Information",
    icon: notionLogo,
    href: "/apps/reader",
    price: "Free",
  },
  {
    id: "readwise",
    name: "Readwise",
    category: "Information",
    icon: notionLogo,
    href: "/apps/readwise",
    price: "Free",
  },
  {
    id: "youtube",
    name: "YouTube",
    category: "Entertainment",
    icon: notionLogo,
    href: "/apps/youtube",
    price: "Free",
  },
  {
    id: "nebula",
    name: "Nebula",
    category: "Entertainment",
    icon: notionLogo,
    href: "/apps/nebula",
    price: "Free",
  },
  {
    id: "kindle",
    name: "Kindle",
    category: "Information",
    icon: notionLogo,
    href: "/apps/kindle",
    price: "Free",
  },
  {
    id: "refind",
    name: "Refind",
    category: "Information",
    icon: notionLogo,
    href: "/apps/refind",
    price: "Free",
  },
  {
    id: "cursor",
    name: "Cursor",
    category: "Development",
    icon: CursorLogo,
    href: "/apps/cursor",
    price: "Free",
  },
  {
    id: "postman",
    name: "Postman",
    category: "Development",
    icon: CursorLogo,
    href: "/apps/postman",
    price: "Free",
  },
  {
    id: "iterm",
    name: "iTerm",
    category: "Development",
    icon: CursorLogo,
    href: "/apps/iterm",
    price: "Free",
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "Development",
    icon: CursorLogo,
    href: "/apps/vercel",
    price: "Free",
  },
  {
    id: "nextjs",
    name: "Next.js",
    category: "Development",
    icon: CursorLogo,
    href: "/apps/nextjs",
    price: "Free",
  },
  {
    id: "github",
    name: "GitHub",
    category: "Development",
    icon: CursorLogo,
    href: "/apps/vercel",
    price: "Free",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "Development",
    icon: CursorLogo,
    href: "/apps/vercel",
    price: "Free",
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "Development",
    icon: CursorLogo,
    href: "/apps/vercel",
    price: "Free",
  },
  {
    id: "linear",
    name: "Linear",
    category: "Productivity",
    icon: LinearLogo,
    href: "/apps/linear",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
  },
  {
    id: "v0",
    name: "V0",
    category: "AI",
    icon: LinearLogo,
    href: "/apps/linear",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
  },
  {
    id: "chatgpt",
    name: "Chat GPT",
    category: "AI",
    icon: LinearLogo,
    href: "/apps/linear",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
  },
  {
    id: "postgresnew",
    name: "pg.new",
    category: "AI",
    icon: LinearLogo,
    href: "/apps/linear",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
  },
  {
    id: "claude",
    name: "Claude",
    category: "AI",
    icon: LinearLogo,
    href: "/apps/linear",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
  },
  {
    id: "tailwind",
    name: "Tailwind",
    category: "Development",
    icon: LinearLogo,
    href: "/apps/linear",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
  },
  {
    id: "x",
    name: "X",
    category: "Social Media",
    icon: LinearLogo,
    href: "/apps/x",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
  },
  {
    id: "instagram",
    name: "Instagram",
    category: "Social Media",
    icon: LinearLogo,
    href: "/apps/instagram",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
  },
  {
    id: "dribbble",
    name: "Dribbble",
    category: "Social Media",
    icon: LinearLogo,
    href: "/apps/dribbble",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
  },
  {
    id: "arc-search",
    name: "Arc Search",
    category: "Productivity",
    icon: LinearLogo,
    href: "/apps/arc-search",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
  },
  {
    id: "halide",
    name: "Halide",
    category: "Creativity",
    icon: LinearLogo,
    href: "/apps/halide",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
  },
  {
    id: "spotify",
    name: "Spotify",
    category: "Entertainment",
    icon: LinearLogo,
    href: "/apps/spotify",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
  },
  {
    id: "logos",
    name: "Logos",
    category: "Information",
    icon: LinearLogo,
    href: "/apps/logos",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
  },
  {
    id: "sequel",
    name: "Sequel",
    category: "Entertainment",
    icon: LinearLogo,
    href: "/apps/sequel",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
  },
  {
    id: "shortcuts",
    name: "Shortcuts",
    category: "Productivity",
    icon: LinearLogo,
    href: "/apps/shortcuts",
    price: "Free",
    description:
      "Linear is a project management tool that helps you manage your projects and tasks.",
  },
];
